name: Dependency Update

on:
  schedule:
    # Run weekly on Sunday at 00:00 UTC
    - cron: '0 0 * * 0'
  workflow_dispatch: # Allow manual triggering

jobs:
  update_dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libasound2-dev \
          pkg-config \
          libpulse-dev \
          libjack-jackd2-dev \
          libpipewire-0.3-dev \
          libspa-0.2-dev

    - name: Install cargo-edit
      run: cargo install cargo-edit

    - name: Update dependencies
      run: |
        cargo upgrade
        cargo update

    - name: Run tests to verify updates
      run: cargo test --all-features
      env:
        RUST_TEST_THREADS: 1

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies'
        title: 'chore: Update Rust dependencies'
        body: |
          This PR updates Rust dependencies to their latest versions.
          
          Changes:
          - Updated Cargo.lock with latest compatible versions
          - All tests pass with updated dependencies
          
          Auto-generated by GitHub Actions.
        branch: chore/update-dependencies
        delete-branch: true