name: Release

env:
  CARGO_TERM_COLOR: always

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Build and Release x86_64 Linux Binary
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-unknown-linux-gnu

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libasound2-dev \
          pkg-config \
          libpulse-dev \
          libjack-jackd2-dev \
          libpipewire-0.3-dev \
          libspa-0.2-dev

    - name: Build release binary
      run: cargo build --release --target x86_64-unknown-linux-gnu

    - name: Strip binary
      run: strip target/x86_64-unknown-linux-gnu/release/hotline

    - name: Rename binary for release
      run: cp target/x86_64-unknown-linux-gnu/release/hotline hotline-linux-x86_64

    - name: Create Release with Assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          hotline-linux-x86_64
          LICENSE
          CHANGELOG.md
        name: HotLine v${{ github.ref_name }}
        body_path: CHANGELOG.md
        draft: false
        prerelease: false
        make_latest: true
        fail_on_unmatched_files: true
        generate_release_notes: true